env:
  browser: true # Adds all browser global variables.

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended

parserOptions:
  project: ./tsconfig.json

settings:
  react:
    version: '17'

rules:
  react/prop-types:
    - off
  react/react-in-jsx-scope:
    - off
  react/require-default-props:
    - off
