env:
  node: true # Adds all Node.js global variables and Node.js scope.

extends:
  - ../.eslintrc.yml

parserOptions:
  project: ./tsconfig.json

overrides:
  - files:
      - knexfile.ts
    rules:
      'import/no-default-export':
        - off
